// global
export const GLOBAL_MAX_WIDTH = 630;
const GLOBAL_PADDING_X = 8;

// header
const GNB_HEIGHT = 50;
const LNB_HEIGHT = 60;
const HEADER_HEIGHT = GNB_HEIGHT + LNB_HEIGHT;

// main
const MAIN_MARGIN_TOP = HEADER_HEIGHT + 10;

export default {
  GLOBAL_MAX_WIDTH,
  GLOBAL_PADDING_X,

  GNB_HEIGHT,
  LNB_HEIGHT,
  HEADER_HEIGHT,

  MAIN_MARGIN_TOP,
};
